name: Deploy Rasa Chatbot
on:
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rasa-chatbot-deploy.yml'
  workflow_dispatch:      

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RASA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RASA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RASA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: ${{ secrets.REGISTRY_URL }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: mindcare-chatbot
          resourceGroup: YOUR_RESOURCE_GROUP
          imageToBuild: ${{ secrets.REGISTRY_URL }}/mindcare-chatbot:${{ github.sha }}
          targetPort: 8080
          ingress: external
          environmentVariables: |
            PORT=8080
            RASA_TELEMETRY_ENABLED=false
            RASA_MODEL_PATH=/app/models
            RASA_ACTIONS_URL=http://localhost:5055
            PYTHONPATH=/app
            RASA_CORS_ORIGINS=* 